export const itemList = [
  {
    _id: 0,
    category: "데일리 정장",
    delivery: "무료배송",
    name: "캐보트 여아 여름 유니콘 원피스 2가지 옵션",
    sale: "50%",
    price: 100000,
    rate: 4.7,
    product: "../image/7.png",
  },
  {
    _id: 1,
    category: "데일리 정장",
    delivery: "무료배송",
    name: "파란색 무도회장 복장",
    sale: "50%",
    price: 70000,
    rate: 4.2,
    product: "../image/8.png",
  },
  {
    _id: 2,
    category: "데일리 정장",
    delivery: "5만원 이상 구매시 무료배송",
    name: "보라카이 가야 할 것 같은 원피스",
    sale: "40%",
    price: 30000,
    rate: 4.7,
    product: "../image/9.png",
  },
  {
    _id: 3,
    category: "데일리 정장",
    delivery: "무료배송",
    name: "원피스 수영복",
    sale: "50%",
    price: 60000,
    rate: 4.7,
    product: "../image/10.png",
  },
  {
    _id: 4,
    category: "데일리 정장",
    delivery: "무료배송",
    name: "프릴 블라우스 - 레드",
    sale: "10%",
    price: 80000,
    rate: 4.7,
    product: "../image/11.png",
  },
  {
    _id: 5,
    category: "데일리 정장",
    delivery: "무료배송",
    name: "인도 전통의상",
    sale: "5%",
    price: 50000,
    rate: 3.2,
    product: "../image/12.png",
  },
  {
    _id: 6,
    category: "데일리 정장",
    delivery: "무료배송",
    name: "빨간 전통의상",
    sale: "50%",
    price: 9000,
    rate: 4.7,
    product: "../image/13.png",
  },
  {
    _id: 7,
    category: "데일리 정장",
    delivery: "무료배송",
    name: "레트로 스타일 셋업",
    sale: "20%",
    price: 40000,
    rate: 4.1,
    product: "../image/14.png",
  },
  {
    _id: 8,
    category: "데일리 정장",
    delivery: "무료배송",
    name: "대용량 스킨",
    sale: "10%",
    price: 50000,
    rate: 4.7,
    product: "../image/15.png",
  },
  {
    _id: 9,
    category: "데일리 정장",
    delivery: "무료배송",
    name: "빈티지 감성 엽서 - 바다를 바라보는 사람들",
    sale: "10%",
    price: 3000,
    rate: 3.7,
    product: "../image/16.png",
  },
];
